# This files takes in data_w_genre, and outputs a JSON file in the format needed by the D3 network graph


import pandas as pd
import json
import networkx as nx
import community.community_louvain as community_louvain

data_file = '../../Data/data_w_genres.csv'
json_save = '../../docs/ChartFiles/coref.json'


def process_genre_list(csv):
    """
    Reads the CSV file containing genre data and converts the genres column (string representation)
    into a list-of-lists. Each inner list corresponds to an entry with one or more genres.
    """
    df = pd.read_csv(csv)
    genres_lists = []
    for i in df['genres']:
        # Converts from str to list
        genres_list = i[1:-1]
        genres_list = genres_list.replace("'", "")
        genres_list = genres_list.split(", ")

        # Skips empty lists and entries with only one genre
        if len(genres_list) >= 2 and genres_list[0] != "":
            genres_lists.append(genres_list)

    unique_genres = []
    for group in genres_lists:
        for each in group:
            if each not in unique_genres:
                unique_genres.append(each)
    return genres_lists, unique_genres


def build_genre_network(genre_entries):
    """
    Given a list of lists (each inner list is an entry with one or more genres),
    build an undirected graph where nodes are genres and edges represent co-occurrence.
    Edge weights count how many times two genres appear together.
    """
    G = nx.Graph()
    for entry in genre_entries:
        if not entry or entry == ['']:
            continue
        # Add each genre as a node
        for genre in entry:
            if genre not in G:
                G.add_node(genre)
        # Add an edge between every pair of genres in the same entry (or increase the weight)
        if len(entry) > 1:
            for i in range(len(entry)):
                for j in range(i + 1, len(entry)):
                    g1, g2 = entry[i], entry[j]
                    if G.has_edge(g1, g2):
                        G[g1][g2]['weight'] += 1
                    else:
                        G.add_edge(g1, g2, weight=1)
    return G


def compute_metrics(G):
    """
    Compute network metrics for nodes in G.
    Returns dictionaries for degree, betweenness, eigenvector centrality,
    degree centrality, and the community partition computed via the Louvain algorithm.
    """
    degree_dict = dict(G.degree())
    betweenness = nx.betweenness_centrality(G, weight='weight')
    eigenvector = nx.eigenvector_centrality(G, weight='weight', max_iter=1000)
    degree_cent = nx.degree_centrality(G)
    partition = community_louvain.best_partition(G, weight='weight') if len(G.nodes()) > 0 else {}
    return degree_dict, betweenness, eigenvector, degree_cent, partition


def build_json_structure(genre_entries):
    """
    Builds the JSON structure for the network.
    Each node represents a genre and includes computed metrics and a 'modularity' value,
    which here is the community id (remapped sequentially) computed via the Louvain algorithm.
    Node 'id' is generated by removing spaces, and a 'name' attribute is included with title-cased genre.
    """
    G = build_genre_network(genre_entries)
    degree_dict, betweenness, eigenvector, degree_cent, partition = compute_metrics(G)


    nodes_list = []
    for genre in G.nodes():
        node_obj = {
            "degree": degree_dict.get(genre, 0),
            "betweenness": betweenness.get(genre, 0.0),
            "eigenvector": eigenvector.get(genre, 0.0),
            "degree_cent": degree_cent.get(genre, 0.0),
            "modularity": partition.get(genre, 0),
            "id": genre.replace(" ", "").replace("-",""),
            "genre_name": genre,
            "name": genre.title()
        }
        nodes_list.append(node_obj)

    links_list = []
    for u, v, data in G.edges(data=True):
        link_obj = {
            "weight": data.get("weight", 1),
            "source": u.replace(" ", "").replace("-",""),
            "target": v.replace(" ", "").replace("-","")
        }
        links_list.append(link_obj)

    metrics = {
        "num_entries": str(len(genre_entries)),
        "num_nodes": len(G.nodes()),
        "num_edges": len(G.edges())
    }

    network_json = {
        "metrics": metrics,
        "directed": False,
        "multigraph": False,
        "graph": {},
        "nodes": nodes_list,
        "links": links_list
    }

    return network_json

# For filtering how many show up.. no filtering you get massive chart
DEFAULT_TOP_N = 10
DEFAULT_MIN_DEGREE = 20


def filter_network_json(network_json, top_n=DEFAULT_TOP_N, min_degree=DEFAULT_MIN_DEGREE):
    """
    Filters the network JSON so that it only includes nodes with degree >= min_degree,
    then selects the top `top_n` nodes (by degree) among them and any nodes connected
    to those top nodes, along with the corresponding links.
    After filtering, the function rebuilds a graph from the filtered nodes and links,
    computes community assignments using the Louvain algorithm on this filtered graph,
    remaps the community IDs sequentially, and updates each node's 'modularity' field accordingly.
    """
    # Filter nodes by minimum degree
    nodes_filtered = [node for node in network_json["nodes"] if node["degree"] >= min_degree]
    valid_ids = set(node["id"] for node in nodes_filtered)

    # Sort nodes by degree descending and select top_n nodes
    sorted_nodes = sorted(nodes_filtered, key=lambda x: x["degree"], reverse=True)
    top_node_ids = set(node["id"] for node in sorted_nodes[:top_n])

    # Include any node (from the filtered set) that is connected to these top nodes
    filtered_links = []
    additional_ids = set()
    for link in network_json["links"]:
        if link["source"] in valid_ids and link["target"] in valid_ids:
            if link["source"] in top_node_ids or link["target"] in top_node_ids:
                filtered_links.append(link)
                additional_ids.add(link["source"])
                additional_ids.add(link["target"])

    final_ids = top_node_ids.union(additional_ids)
    filtered_nodes = [node for node in nodes_filtered if node["id"] in final_ids]

    # Rebuild a graph from the filtered nodes and links
    G_filtered = nx.Graph()
    for node in filtered_nodes:
        G_filtered.add_node(node["id"])
    for link in filtered_links:
        G_filtered.add_edge(link["source"], link["target"], weight=link.get("weight", 1))

    # Compute community assignments using Louvain on the filtered graph
    new_partition = community_louvain.best_partition(G_filtered, weight='weight') if len(G_filtered.nodes()) > 0 else {}

    # Remap community IDs to sequential values
    unique_groups = sorted(set(new_partition.values()))
    group_mapping = {group: idx for idx, group in enumerate(unique_groups)}

    # Update each node's modularity with the remapped community ID
    for node in filtered_nodes:
        node_id = node["id"]
        node["modularity"] = group_mapping.get(new_partition.get(node_id), 0)

    # Update the network_json structure
    network_json["nodes"] = filtered_nodes
    network_json["links"] = filtered_links
    network_json["metrics"]["num_nodes"] = len(filtered_nodes)
    network_json["metrics"]["num_edges"] = len(filtered_links)

    return network_json


def main():
    # Process the CSV to get a list-of-lists for the genres
    genre_entries, uniques = process_genre_list(data_file)

    # Build the full JSON structure from the genre entries
    network_json = build_json_structure(genre_entries)

    # Filter the network to keep only the top n nodes and their connected nodes (default n=10)
    filtered_network = filter_network_json(network_json, top_n=DEFAULT_TOP_N, min_degree=DEFAULT_MIN_DEGREE)


    # Write the filtered JSON to a file
    with open(json_save, "w") as f:
        json.dump(filtered_network, f, indent=4)

    print("JSON network file has been created as " + json_save)


if __name__ == '__main__':
    main()